
# Peer Production Adaptation Paper-Open Deliberation 

## Introduction

The paper aims to bring out communities that use open deliberation to make decisions. The paper focuses on the functional structure of these communities and underlines the principles that match closely to the principles of peer production. It illustrates the idea of open deliberation citing examples in various fields and how the challenges were overcome to result to the final outcome in the respective fields.

## Methodology

The paper was written by doing an extensive research of the UT library databases and Google scholar articles. The paper also has included the concepts of the Peer Production class of UT Austin. The research involved survey of a candidate who has been involved in leading protests in the campus of UT Austin against the Tax Bill passed by the US Government in 2017.

## Meaning of Open Deliberation

Open deliberation implies collective decision making process. "Designing organizations and management with a positive lens requires the enabling of positive forms of inquiry that are open-ended, appreciative, relatively free from social controls and carried out in the spirit of open-mindedness, mutual respect and understanding."(Asif & Klein, 2009) The purpose of open deliberation is to have a positive inquiry and inputs from people involved in the community that will eventually help in the decision making process. Creation of new ideas or systems requires people from different backgrounds to understand the different processes involved in the implementation. Positive criticism and deliberative inquiry help improve a system. There are several communities who work with the idea of open deliberating in order to produce the final outcome that could potentially benefit everyone involved in the community. 

## Communities indulging in the act of Open Deliberation

One of the most important communities using the technique of open deliberation is democracy. "Deliberative democracy involves discussion between citizens, and promotes direct engagement on complex moral and political issues."(Hagendijk & Irwin, 2006). Democracy is defined as the government of the people, for the people and mostly important BY the people. By involving the public in most of the socio-economic factors the final outcome would be fruitful for the entire community. (Hagendijk & Irwin, 2006) clearly points out to the fact that involving a varied group of people in the collective decision making will guarantee unbiased outcome favourable for the overall growth of the community. One of the reasons of using deliberative democracy is that "theorists have contended that decisions resulting from deliberation will be more informed and rational, that they will reflect a more equal consideration of interests, that they will be less likely to infringe on individual rights, and that such decisions will be more legitimate."(Fung, 2005) Most of the times decisions taken by government taken by officials can lack a view of the people that going to be affected by it. This makes it necessary to have a group of people from different backgrounds express their views on any decision that can have socio-economic implications.
One of the modifications of open deliberation in governance are communities or groups that closely work together to achieve a social cause like protest groups or NGOs. The decisions taken in this community are a collective effort of the members of the community. They work together to improve upon an existing system. People with a common objective of opposing laws or helping people come together to form a community and collectively decide on the course of action. The basic motive behind this activity is to improve the existing system.
Another important kind of open deliberation seen in specific hierarchy of companies is corporate deliberation. This shows how "organizations can harness their employees' wisdom to bring to the table cutting-edge ideas, debate their relevancy to the organization, agree collectively on their vision for the future and generate applicable ideas toward realizing their preferred future image."(Passig, Cohen, Bareket-Bojmel, & Morgenstern, 2015).Corporate organizations often have a board of directors along with whom the CEO discusses factors and implications before taking any important decisions. Similarly at different hierarchies of the company, the managers function in an agile manner where the managers often have scrum meetings to discuss the sprints that their team has to complete and discuss the challenges faced by the team.
One of the interesting illustrations in the field of open deliberation is the community of justice. "A form of such public engagement has been used in the field of criminal justice for centuries in the form of the jury." The court has a panel of participants called the jury which carefully listen to both the sides of the argument and then collectively takes a decision. This has potential benefits of considering the case from different angles and thus giving unbiased judgements. This is particularly more fruitful than a single judge deciding the punitive action that should be taken against the accused. The jury is a "group of citizens is engaged in a particular manner so that they become highly informed and responsible and, as much as possible, they are encouraged to deliberate deeply."(Indermaur, Roberts, Spiranovic, Mackenzie, & Gelb, 2012)

## Need and Advantages of Open Deliberation

The important parameters that should be considered while dealing with open deliberation are the needs and advantages. "Participation in a deliberative polling event would be associated with a shift in attitudes and an increase in general knowledge about the subject." (Latimer, Hempson, & Kendrick, 1960). One of the most important advantage of deliberative action is awareness about the factors involved in the decision making process that could affect their lives in the future. People vote for their leaders in a democracy and expect them to do good for the community. The overall process of selecting candidates by a collective effort to bring about a decision as to who should be elected is again an example of open deliberation. The assessment in most of the cases like election is done through votes/polls. The majority in a community decides the course of action for the activity. The awareness and inquiry about issues in any community leads to positive criticism thus elaborating scope for improvements. 
"All forms of official governance respond to some felt need, and as perceptions of that need changes"(Goodman & Sydney, 2012). The need felt by the people to alter a current on-going system in order to produce a better output leads to deliberation. The need for open deliberation is to taken into consideration thought process of all/many people associated that can debate/discuss plausible improvements and modifications and the result would be a collective outcome thus enhancing the overall performance. This need contributes as a motivating factor for people to get involved and contributes inputs to the system.


## Challenges of Open Deliberation

One of the most important challenges for open Deliberation is motivation. "Citizens ought to be interested not just in maintaining a coherent and defensible value set but in reformulating it when new evidence and compelling counterarguments"(Smith, 2014) One must take interest in participating in open deliberation. There are new ideas and exchange of thoughts only when many people can actively contribute to the system.
Another challenge in open deliberation is the level of assessment. "Develop criteria to allow assessment of the legitimacy or otherwise of certain forms of the deliberation"(McDonald, 2011) Even though the decision is a collective effort it can be wrong since there is no measure of assessment to judge the accuracy of the efforts of each participants. Just as in production a single failure may lead to the overall failure of the system, it might happen that a few wrong thoughts or perceptions influence others and it may lead to an overall bad decision.
Selection of candidates that take decision is another challenge for open deliberation. "Deliberators must engage with one another on the basis of accessible reasons, and the concerns of all must be given fair and unprejudiced consideration"(Smith, 2014). Sometimes it not possible for all the members of the community to actively contribute to the community and so candidates are elected which in turn represent the entire community and these candidates collectively take decisions. The selection of these candidates is an important process which governs the overall functioning of the decision making process. It can be the scenario that the candidates chosen can be biased towards a particular section of the community thus forfeiting the entire purpose of open deliberation. Thus it should be made sure that the candidates chosen represent different sections of the community with different backgrounds thus giving proper thought to different implications before taking any decisions.

## Assessment of Survey

The survey involved a student of UT Austin who lead the protests against the passing of Tax Bill by the US government in 2017. The interview started with greetings and then questions were asked to gain insights about the functioning of the community. The interviewee had been constantly involved in protesting against the laws that were considered "inhuman" or "non-moral" by their group. The question of the reason to protest was answered as the fight for students who would suffer huge losses if the tuition waivers were taxed. The next question was about the strength of their community to which the interviewee replied as 29 active members and 13-15 silent members. The next question was how were the topics of the protests decided? The interviewee replied that the group meets on third Thursday of every month to talk and discuss on social issues that could deeply affect student life. The next question involved how are decisions taken in matters of a conflict? The interviewee replied that most of the decisions are taken on the basis of the votes. These votes are taken after both the conflicting parties speak about their stand and then the decision is based on the highest number of votes. The next question was how were the protests or movements improved to which the interviewee answered that the group meeting would start of by discussing about their previous assignment, mistakes that made, challenges they faced and good things that came out from the movement. After the discussion they would propose alterations to the upcoming movements. The next question was what are the advantages of working in an open deliberative community where decisions are based on collective inputs? The interviewee responded that the final outcome would include the collective action of all the members and everyone would be aware of the consequences as well. The last question was what kind of challenges does the group face while working in an open deliberative community? The interviewee responded that sometimes it is difficult to respect each and every opinion while formulating the final outcome but as long as the majority is happy it is fairly a good outcome. Also at times it is difficult to get more people involved or motivate people to join the movement but most of the times a common interest towards the goal drives people forward to help them.

## Conclusions

The analyses of open deliberation in different communities lead to drawing out a few hypotheses based on literature evidence.  The first hypothesis is that open deliberation plays a crucial role in creating awareness among people involved in the community with regards to socio-economic factors involved in the final decision making. Also, including people in debates or discussions leads to an unbiased point of view by taking in consideration the views or perception of many people involved. The main motivation behind people getting involved in open deliberation is an effort to create a better decision which would impact their lives in a positive manner. People working together as a community towards fulfilling a common goal will work much faster and have more clarity than working with a centralized power. The above factors clearly represent that people working on a particular decision and improving each step along the way is an overall adaptation of peer production.

## References

Asif, Z., & Klein, H. K. (2009). Open and free deliberation: A prerequisite
for positive design.   Information and Organization, 19(3), 186-197.        <https://doi.org/https://doi.org/10.1016/j.infoandorg.2009.04.003>

Fung, A. (2005). Deliberation before the Revolution: Toward an Ethics of    Deliberative Democracy in an Unjust World. Political Theory, 33(3),          397-419. <https://doi.org/10.1177/0090591704271990>

Goodman, J., & Sydney, T. (2012). Disorderly Deliberation???? Generative Dynamics of Global Climate Justice, 8(3), 1-21.

Hagendijk, R., & Irwin, A. (2006). Public Deliberation and Governance: Engaging with Science and Technology in Contemporary Europe. Minerva, 44(2), 167-184. <https://doi.org/10.1007/s11024-006-0012-x>

Indermaur, D., Roberts, L., Spiranovic, C., Mackenzie, G., & Gelb, K. (2012). A matter of judgement: The effect of information and deliberation on public attitudes to punishment. Punishment & Society, 14(2), 147-165. <https://doi.org/10.1177/1462474511434430>

Latimer, C., Hempson, K., & Kendrick, J. R. (1960). A Community Deliberative Polling Event???: The Economic Impact of Walmart, 4(2), 40-52.

McDonald, M. (2011). Deliberation and Resecuritization: Australia, Asylum-Seekers and the Normative Limits of the Copenhagen School. Australian Journal of Political Science, 46(2), 281-295. <https://doi.org/10.1080/10361146.2011.568471>

Passig, D., Cohen, N., Bareket-Bojmel, L., & Morgenstern, O. (2015). Crowd-deliberation as an organizational problem solving tool. International Journal of Manpower, 36(7), 1124-1143. <https://doi.org/10.1108/IJM-03-2014-0075>

Smith, A. F. (2014). Political deliberation and the challenge of bounded rationality. Politics, Philosophy & Economics, 13(3), 269-291. <https://doi.org/10.1177/1470594X13488355>






