---
output:
  word_document: default
  html_document: default
---

# Peer Production Adaptation at BMW
Author - Nimish Kate

## Introduction  
The BMW group has been attempting to apply the open source development theory in its new automobile development projects. Hundreds of team members work from their homes to contribute to BMW's research and development center. These team members include people from a variety of department, and collaborate in an open source environment to build prototype designs for BMW cars. The designs are taken into consideration by the in-house research and development teams at BMW, with many of them end up in actual implementations. The paper discusses the approaches taken by BMW to adapt peer production concepts in their research and development projects, and analyzes the challenges faced during the said adaptations.

The open source department at BMW has five major projects - joynr, ConnMan, Etch, IVI Layer Management, and Sphinx, which are managed by BMW Car IT GmbH, a software company that is a subsidiary of the BMW group. The company is responsible for all the software projects applied in BMW cars. Apart from the in-house research and development, BMW Car IT GmbH has over 35 github repositories for different projects, where people collaborate their ideas and expertise in building or improving the softwares used in BMW cars. These repositories deal with small technological advances like offline map matching (matching a sequence of GPS coordinates to road segments), to larger projects mentioned above. This paper will briefly discuss the six projects and the role of open source collaboration in their implementations.

- joynr  
"joynr is a fault-tolerant, typed communications-middleware abstraction framework for applications and services deployed to vehicles, consumer devices, web browsers and backend servers that need to interact with each other1." joynr is a web-based communication framework that enables C++, Java, and Javascript applications to interact with one another, post deployment on multiple devices like mobile phones, cars or backend infrastructures. BMW Car IT GmbH maintains the joynr project, implementing the applications built by people in a way that they link to services in BMW cars.

- ConnMan  
The ConnMan project is a connection manager designed to manage internet connections within embedded devices that run on the Linux OS. Various external environmental features like traffic updates, news reports, weather updates are embedded into features in BMW cars using applications built on the ConnMan project. The top contributors from BMW Car IT GmbH have acted as the maintainers of the ConnMan project.

- Etch  
The Apache Etch framework is the fundamental communication protocol used for BMW apps, a list of smartphone applications that manage features in BMW cars. The Etch project is an open source collaboration project which helps the framework connect smartphones to the vehicle's head unit, enabling an efficient bidirectional communication system.

- IVI Layer Management  
The IVI (in vehicle infotainment) systems provide multimedia and navigation services in automobiles. BMW Car IT GmbH initiated the IVI Layer Management project in 2009, which is range of components that assist in rendering complex layers of services provided by IVI systems. Various companies contribute to the IVI Layer Management project, while BMW Car IT GmbH integrates patches and deploys updates regularly.

- Sphinx  
The Sphinx project is an open source project under Eclipse, which provides functionality to create integrated modeling tool environments for various modeling languages. BMW Car IT GmbH adapts developments from the Sphinx project, where contributors work on building navigator views and runtime extensions.
Apart from these projects, BMW Car IT GmbH developed the iDrive technology, which is an integrated control system for all the features in a BMW vehicle. The iDrive is a unified system that allows control to amenities such as climate, audio, navigation, and mobile communications. The iDrive applies the joystick technology from the local gaming industry to control more than 700 functions in the BMW 7 series. The iDrive technology was built by BMW by pairing up with Immersion, a high-tech company with no experience in the automobile industry (Gassmann, 2004). IBM developed a vision "Computer on wheels based on BMW's research and data for the iDrive technology. This strategic alliance with IBM helped imrove the iDrive. The business models of these companies have been completely different from those of BMW's, but the collaboration has worked out to help BMW rise as a leader in automobile innovation (Frankenberger et. Al. 2004).

## Motivations  
The world of automobiles has seen revolutionary changes over the decades. There is a huge amount of competition among different brands, with technology gaining importance to be in the center of everything. At times, there have been developments that have revolutionized the entire automobile industry, like the invention of power steering, with almost everyone incorporating these developments in their cars. Such changes have reached to every car owner in the world, and people have had increasing opinions about them. People from various backgrounds and industries possess skills that can help improve the technologies in cars. In the competitive world, a car brand cannot employ all the best talent in the world and the BMW group has long acquired that revelation. This has led to intrinsic motivation of open collaboration projects where people contribute to improve the technology in BMW cars. The BMW group is motivated to adhere to open collaboration norms and maintain the level of transparency, as it helps them compete with cars built by other automobile brands. There is also some motivation about marketing and public relations, as the open source aspect has been seen to improve BMW's image in the eyes of the general public.

While peer production primarily dominates the software industry, certain aspects of open collaboration can be implemented in design technology in practically any industry. The BMW group has smartly utilized open collaboration aspects into designing, prototyping and improving their cars. The contributors to the open collaboration projects are motivated by the BMW brand association. Contributors get to witness their contributions implemented by a global brand like BMW, in terms of car designs, services, and features like safety, navigation, multimedia etc. The technology of BMW's electric cars is the biggest entrance to the world of open collaboration in BMW, says Devesh Gadkari, a technology executive at Drivhuset, Stockholm. Gadkari works with Funnel.io, an integration platform that allows clients to gather data from over 400+ data sources at a time, and the Funnel integrates it for the clients. As a part of Funnel, Gadkari had a chance to collaborate to the BMW i3 and the BMW i8 firmware. In this project, he worked to integrate web browsers with the iDrive console. He elaborates the motivations for working over the project as completely intrinsic. He explains that there is no reward, payment, or prize, yet the idea of contributing to the development of a BMW car, which will be imprinted on the car all over the world, is a reward in itself. This motivation drives people all over the world to contribute to one or more aspects of BMW's technology.

## Challenges  
The BMW automobile research and development team operates their iDrive technology under a GPL, implemented in their cars. In a recent internet tussle, a blogger Terence Eden found issues in the firmware and software of his BMW i3. He requested BMW to send over their source code for him to analyze. The BMW headquarters had to comply, under the terms of the GNU General Public License, and they mailed him a DVD of the entire source code. Gadkari had researched this topic before he began to work on the BMW i3 technology, and had some light to shed on the matter. The BMW group, in its vast documentation about the services and products, has documentation about what parts of the car's software are under the GNU General Public License. The company is very specific about parting with its code. The open source concept dictates a few terms for something to be considered as open source. According to Benkler (2009), peer production lies on three dimensions - decentralized conception and execution, diverse motivations, and organizational governance. In case of the open source in BMW Car IT GmbH, the decentralization of conception and execution is insignificant. The motivations appear to be diverse, as some collaboration is monetary, with firms partnering with BMW Car IT GmbH. Meanwhile, a few collaboration efforts are non-monetary and intrinsic, like the work that Devesh Gadkari did. These terms allow the effort to border on open collaboration, rather than peer production. The difference between BMW and other companies using the open source way is the separation between governance and ownership. BMW builds a part of the code and then uses Github extensively to allow people to engage in collaborations. Despite owning part of the code, it is filed under the GNU General Public License, making it as close as possible to the concept of peer production. The challenge here, as Gadkari says, is making the software available to people. BMW Car IT GmbH has open source projects on Github for which they need people to collaborate together. But, code that has already been filed under the GNU General Public License, is possessed by the BMW group. In order for someone to have access to this code, additional hassle is required. As it was in the case of the blogger Eden, he had to get in touch with the legal offices of BMW for a while before they reacted. BMW ended up mailing a DVD with the source code to Eden, which he later mirrored and uploaded on his Github account. The product licensing terms are known to a select few, according to Gadkari, as seldom does a person come along and ask to see the licensed source code. This case of Eden's dilemma was one of the many softwares that may have been filed under the GNU General Public License, but overlooked by contributors. This is a big challenge for a company like the BMW group, where they expect collaborators to help with the software and firmware aspects, as well as automobile design prototyping. The designing aspect, according to Gadkari is another major challenge, as open source dictates separation of ownership and governance. A collaborator can claim ownership to his design, as his work is not bound by licensing terms. Once the work is uploaded and patched to the BMW's software, BMW holds ownership to the code. The infrastructure of BMW's open collaboration is primarily handled by its github repositories, managed by BMW Car IT GmbH. The sections not published on open platforms have unclear infrastructure, as BMW has collaborations with other organizations as well who may not have filed the said products or services under the GNU General Public License. These complex legalities lead to a hindrance in a seamless open source collaboration.

## Conclusion  
The study focused on the BMW group's open source collaboration efforts. BMW Car IT GmbH, a subsidiary of the BMW group, manages open source collaboration projects on Github, where contributors help develop and improve softwares, services, and features for the firmware used in BMW automobiles. The BMW group also allows certain aspects of their research and development to be utilized in open collaboration environments, by filing these aspects under the GNU General Public License. The study interviewed Devesh Gadkari, who works in a Stockholm based firm that specializes in integrating services. Gadkari narrates his experiences in collaborating for BMW's service integration with iDrive technology, the system that integrates all vehicular controls together. The study discusses the challenges faced by BMW and by collaborators while adhering to the open source standards, and issues that arose due to legalities. The study concludes with a comparison between BMW's open environment to open collaboration as well as peer production concepts, and attempts to classify the environment into either of the two categories.

## Bibliography  

1. http://www.bmw-carit.de/open-source/
2. Gassmann, O., & Enkel, E. (2004). Towards a theory of open innovation: three core process archetypes.
3. Frankenberger, K., Weiblen, T., & Gassmann, O. (2014). The antecedents of open business models: an exploratory study of incumbent firms. R&D Management, 44(2), 173-188.
4. Benkler, Y. (2016). Peer production and cooperation. Handbook on the Economics of the Internet, 91.
5. https://gigazine.net/gsc_news/en/20160331-bmw-gpl/
6. https://github.com/bmwcarit
